- name: "Add an agent user"
  user:
    name: "{{ agent_user }}"
    group: "{{ agent_user }}"
    comment: "Azure DevOps Agent"
    shell: /bin/bash
  become: true
  tags: azuredevops

- name: "Check AzureDevOps Agent version"
  become_user: "{{ agent_user }}"
  azure_devops:
    action: check_version
  register: is_version_valid
  tags: azuredevops

- name: "Download Azure DevOps Agent"
  become_user: "{{ agent_user }}"
  azure_devops:
    action: download
    agent_download_url: "{{ agent_download_url }}"
  ignore_errors: true
  tags: azuredevops
  when: is_version_valid.changed | bool

- include_tasks: configure_azagent.yml
  when: is_version_valid.changed | bool

- name: Start Agent
  become_user: "{{ agent_user }}"
  become: true
  become_method: sudo
  azure_devops:
    action: start
    agent_user: "{{ agent_user }}"
    agent_installation_directory: "{{ agent_installation_directory }}"
  ignore_errors: true
  tags: azuredevops
